import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Old shared links on the vercel.app domain → custom domain.
      // /api is left alone so the cron and any external callers keep working.
      {
        source: "/:path((?!api/).*)",
        has: [{ type: "host", value: "baseball-hopper.vercel.app" }],
        destination: "https://baseballhopper.com/:path",
        permanent: true,
      },
    ];
  },
  async rewrites() {
    return [
      // xR page is regenerated by the xR bot in willybeanes/xr-philosophy;
      // proxy it so /xr always shows the latest scores.
      {
        source: "/xr-app",
        destination: "https://willybeanes.github.io/xr-philosophy/app.html",
      },
    ];
  },
};

export default nextConfig;
