import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async rewrites() {
    return [
      // xR page is regenerated by the xR bot in willybeanes/xr-philosophy;
      // proxy it so /xr always shows the latest scores.
      {
        source: "/xr-app",
        destination: "https://willybeanes.github.io/xr-philosophy/app.html",
      },
    ];
  },
};

export default nextConfig;
